# Generated by Django 5.1.6 on 2025-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular Customer'), ('premium', 'Premium Customer'), ('seller', 'Seller')], default='regular', max_length=10),
        ),
    ]
